#!/bin/sh /etc/rc.common

START=99
STOP=50
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/mgmt-alias-iface
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}