#
# Copyright 2022 Morse Micro
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Morse Micro Theme
LUCI_DEPENDS:=

PKG_LICENSE:=Apache-2.0

#include ../../luci.mk
include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
