include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Morse Guide URL Link (no offline PDF included)
LUCI_DEPENDS:=+luci-base +luci-app-morseconfig
LUCI_DESCRIPTION:=This package provides a URL link to the Morse OpenWrt User Guide instead of the providing the full PDF.

include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature
