#
# Copyright 2024 Morse Micro
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Morse Micro Argon Theme
LUCI_DEPENDS:=

PKG_LICENSE:=Apache-2.0

CONFIG_LUCI_CSSTIDY:=

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
