#!/bin/sh /etc/rc.common

STOP=10
USE_PROCD=1
SERVICE=dppd

. /usr/share/libubox/jshn.sh


get_ap_config() {
        ubus_output=$(ubus call network.wireless status)
        json_init
        json_load "$ubus_output"
        json_get_keys radios
        for radio in $radios; do
                json_select "$radio"

                json_select config
                json_get_vars band
                json_select ..

                json_select interfaces
                json_get_keys interfaces
                for interface in $interfaces; do
                        json_select "$interface"
                        json_get_vars ifname
                        json_select config
                        json_get_vars mode encryption key
                        json_select ..
                        json_select ..

                        if [ "$band" = s1g -a "$mode" = ap ] && [ "$encryption" = sae -o "$encryption" = sae-mixed ]; then
                                json_select ..
                                json_select ..
                                return 0
                        fi
                done
                json_select ..

                json_select ..
        done

        return 1
}


start_service() {
        if ! get_ap_config; then
                logger -t $SERVICE -p daemon.crit "No AP on s1g device with encryption as sae/sae-mixed"
                return 1
        fi

        local ctrl_if_path="/var/run/hostapd_s1g/$ifname"
        if ! [ -e "$ctrl_if_path" ]; then
                logger -t $SERVICE -p daemon.warn "Unable to find hostapd control interface in /var/run/hostapd_s1g; retrying after 1 sec..."
                sleep 1

                if ! [ -e "$ctrl_if_path" ]; then
                        logger -t $SERVICE -p daemon.crit "Unable to find hostapd control interface in /var/run/hostapd_s1g"
                        return 1
                fi
        fi

        procd_open_instance
        procd_set_param command dppd --ctrl-if-path="$ctrl_if_path" --passphrase="$key"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_append_param command --http-secrets=/etc/dppd/auth_secrets.txt
        procd_append_param command --tls-cert=/etc/dppd/server.pem --tls-key=/etc/dppd/server.key
        procd_append_param command --configurator-key=/etc/dppd/key.pem --configurator-private-key=/etc/dppd/ppkey.pem
        procd_append_param command daemon
        procd_set_param limits as="15000000 15000000"
        procd_set_param respawn 3600 5 50
        procd_close_instance
}
