#!/bin/sh

# This file applies the 'default' wifi setup for Morse devices. Compared to the default
# UCI wifi setup (constructed by the hotplug), this _enables_ the wifi-device by default,
# which leads to default Access Points on the lan.
# Also, if we have information (i.e. region/wifi key) from persistent-vars-storage.sh, this
# is used, otherwise we fall back to randomisation for the wifi key (and no country,
# which means the default AP will _not_ be active for HaLow).
# Since it should only be run after hotplug, and it's designed for Morse products, we keep
# it out of board.d.

. /lib/functions.sh
. /lib/netifd/morse/morse_utils.sh
. /lib/functions/system.sh

LOGTAG="morse-wireless-defaults"

default_ssid=$(uci get system.@system[0].hostname 2>/dev/null)
default_wifi_key="$(persistent_vars_storage.sh READ default_wifi_key)"
if [ -z "$default_wifi_key" ]; then
	default_wifi_key=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 8)
fi
uci set "system.@system[0].default_wifi_key=$default_wifi_key"
mm_region="$(persistent_vars_storage.sh READ mm_region)"

_get_iface() {
	uci get "wireless.default_$1.$2"
}

can_validate_country() {
    ubus call iwinfo countrylist "{\"device\":\"$1\"}" >/dev/null 2>&1
}

is_valid_country() {
	ubus call iwinfo countrylist "{\"device\":\"$1\"}" \
		| jsonfilter -e "@.results[@.code=\"$2\"]" >/dev/null 2>&1
}

_change_device_defaults() {
	local config="$1"

	# If the device is enabled, it's already mutated from its default config
	# so we shouldn't touch it.
	config_get disabled "$config" disabled
	if [ "$disabled" != 1 ]; then
		return
	fi

	# Only setup one device in each band.
	config_get device_band "$config" band
	if eval "[ device_band_$device_band = 1 ]"; then
		return 1
	fi
	eval "device_band_$device_band=1"

	config_get type "$config" type

	# If switching between morse and mac80211 S1G drivers, any existing country
	# should have been retained (APP-6398), which we will try to reuse here.
	# The hotplug may have filled in a default country too.
	local effective_country

	# The locked region must always take precedence
	if [ -n "$mm_region" ]; then
		effective_country="$mm_region"
	else
		config_get effective_country "$config" country
	fi

	if [ "$type" = mac80211 -a "$effective_country" = EU ]; then
		# EU is not a valid country code, and can't be used for non-HaLow WiFi.
		# Default to DE as a reasonable stop-gap.
		effective_country='DE'
	fi

	if [ -n "$effective_country" ] &&
		can_validate_country "$config" &&
		! is_valid_country "$config" "$effective_country"; then
		echo "$LOGTAG: Unsetting invalid country $effective_country for $config" > /dev/kmsg
		uci delete "wireless.$config.country" > /dev/null 2>&1
		effective_country=''
	fi

	# Only change if it's in the default state (i.e. default ssid and key),
	# otherwise we're probably running on a sysupgrade. Note that the country
	# may have been retained by the during an S1G driver switch, but all
	# other configs will remain default due to the hotplug.
	local default_encryption
	if [ "$type" = morse ] &&
		[ "$(_get_iface "$config" ssid)" = MorseMicro ] &&
		[ "$(_get_iface "$config" mode)" = ap ] &&
		[ "$(_get_iface "$config" encryption)" = sae ] &&
		[ "$(_get_iface "$config" key)" = 12345678 ]; then
		# It's probably been setup by our HaLow hotplug.

		# Select an appropriate channel if we have a region.
		# Probably this should be pushed down into netifd-morse.
		if [ -n "$effective_country" ]; then
			# Start on the middle channel of the max bandwidth for the country code.
			# Channels can be queried from iwinfo or the driver, but not if the
			# device is down, and the device is not up until we have a valid channel.
			local bandwidth="$(awk -F, '$1==cc && $3 == "True" && $4 > max {max=$4} END {print max}' \
				cc="$effective_country" /usr/share/morse-regdb/channels.csv)"

			# NB channel selection is no longer necessary, as we have
			# moved to the default OpenWrt behaviour of using ACS if
			# the channel is not set (and use the max bandwidth).
			# However, for now we only make it the explicit default
			# in EU/GB, where it is required.
			local channel
			if [ "$effective_country" = EU -o "$effective_country" = GB ]; then
				channel=auto
				uci set "wireless.$config.s1g_chanbw=$bandwidth"
			else
				channel="$(awk -F, '$1==cc && $3 == "True" && $4==bw {print $8, $5}' \
					cc="$effective_country" bw="$bandwidth" /usr/share/morse-regdb/channels.csv \
					| sort -n | awk '{a[NR]=$2} END {print a[int((NR+1)/2)]}')"
			fi

			uci set "wireless.$config.channel=$channel"
			echo "$LOGTAG: setting $config to $effective_country on channel $channel" > /dev/kmsg
		fi
	elif [ "$type" = mac80211 ] &&
		[ "$device_band" = s1g ]; then
		# If the native S1G device's country is not set, keep it disabled.
		[ -z "$effective_country" ] && return

		# Set a default channel for known-compatible regions.
		case "$effective_country" in
				AU|CA|US)
						# APP-6398: set a default channel known to work with Native S1G.
						uci set "wireless.$config.channel=41"
						uci set "wireless.$config.s1g_oper_chwidth=3"
						echo "$LOGTAG: setting $config to $effective_country on channel 41" > /dev/kmsg
						;;
				*) return ;;
		esac
	elif [ "$type" = mac80211 ] &&
		[ "$(_get_iface "$config" ssid)" = OpenWrt ] &&
		[ "$(_get_iface "$config" mode)" = ap ] &&
		[ "$(_get_iface "$config" encryption)" = none ]; then
		# It's probably been setup by the mac80211 hotplug
		uci set "wireless.default_$config.encryption=psk2"

		# If it's 2.4Ghz radio, choose channel 6 to get highest TX power.
		[ "$device_band" = 2g ] && uci set "wireless.$config.channel=6"
	else
		return
	fi

	[ -n "$effective_country" ] && uci set "wireless.$config.country=$effective_country"

	uci batch <<- END
		delete wireless.$config.disabled
		set wireless.default_$config.ssid='$default_ssid'
		set wireless.default_$config.key='$default_wifi_key'
	END
}

# Wait if we need to for the S1G hotplug to finish, since we can
# be reasonably sure that there should be a S1G device.
# This isn't a proper solution to this problem (i.e. the raciness
# of the hotplug vs uci-defaults), but we also can't trivially
# attach to the existing hotplug because the uboot env setup only
# runs in uci-defaults (and we sometimes need this for
# persistent_vars_storage.sh).
wait_for_s1g_device() {
	local found_device=0
	local attempt

	for attempt in 1 2 3 4 5; do
		_find_s1g_device() {
			local band
			config_get band "$1" band
			if [ "$band" = s1g ]; then
				found_device=1
			fi
		}

		config_foreach _find_s1g_device wifi-device

		if [ "$found_device" = 1 ]; then
			return
		fi

		sleep 1
		config_load wireless
	done
}

config_load wireless
wait_for_s1g_device
config_foreach _change_device_defaults wifi-device
