#!/bin/sh

. /lib/functions.sh

fix_morse_path() {
	local config="$1"
	config_get type "$config" type
	[ "morse" = "$type" ] || return 1
	uci get wireless."${config}".path | grep -q "platform/10130000.sdhci" || return 1
	uci set wireless."${config}".path="$(uci get wireless."${config}".path | sed "s|platform/10130000.sdhci|platform/10130000.mmc|")"
}

remove_redundant_mmc() {
	local config="$1"
	config_get radio "$config" device
	config_get type "$radio" type

	# quit if morse - don't want to nuke existing config
	[ "morse" = "$type" ] && return 1
	uci get wireless."${radio}".path | grep -q "platform/10130000.mmc" || return 1

	uci delete "wireless.$config"
	uci delete "wireless.$radio"
}

config_load wireless

# we only bother doing this replacement if we now have the mt7620 mmc loaded
grep -q "mediatek,mt7620-mmc" "/sys/devices/platform/10130000.mmc/of_node/compatible" 2>/dev/null || return 0


config_foreach fix_morse_path wifi-device
config_foreach remove_redundant_mmc wifi-iface
uci commit wireless