#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh

# Do not change the password if this is an upgrade.
if [ -f /sysupgrade.tgz ]; then
	exit 0
fi

# NB persistent_vars_storage.sh may not be present, in which case
# this command will generate no output. This is expected.
password="$(persistent_vars_storage.sh READ device_password)"
if [ -n "$password" ]; then
	passwd root > /dev/null 2> /dev/null <<END
$password
$password
END
fi

exit 0
