#!/bin/sh /etc/rc.common

START=99
boot() {
	(
		# Wait so that the network settles, including association/DHCP client.
		sleep 25
		# Send output to TMPFILE to avoid /dev/kmsg interleaving from other outputs.
		TMPFILE="$(mktemp)"
		/morse/scripts/morse-mode-print.sh > "$TMPFILE"
		cat "$TMPFILE" > /dev/kmsg
		rm -f "$TMPFILE"
	) & 
}
