#!/bin/sh /etc/rc.common

# Must be after uhttpd.
START=99

# We use procd not because we're a legit service - this is a script
# that runs only to do reconfiguration - but so we can
# easily rerun on changes to wireless/prplmesh config.
USE_PROCD=1

start_service() {
	if [ "$(uci get wizard-config.main.server)" != 1 ]; then
		return
	fi

	procd_open_instance wizard-config
	procd_set_param command wizard-config server
	procd_set_param stdout 1
	procd_set_param stderr 1
	# Our ucode script reads these directly, so we tell procd we rely on them
	# so it knows to restart us if they change.
	procd_set_param file /etc/config/wireless
	procd_set_param file /etc/config/prplmesh
	procd_close_instance
}

stop_service() {
	# Tell wizard-config that we're stopping (i.e. remove umdns stuff).
	wizard-config serverstop
}

service_triggers() {
	procd_add_reload_trigger wireless prplmesh
}
