#
# Copyright 2024 Morse Micro
#
# This is free software, licensed under the 3-Clause BSD License.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI VivaGraphJS library
LUCI_MAINTAINER:=Morse Micro
LUCI_URL:=https://github.com/anvaka/VivaGraphJS/
LUCI_SUBMENU:=6. Libraries
LUCI_DESCRIPTION:=minified VivaGraphJS javascript library

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
