#!/bin/sh

. /lib/functions.sh

# Previously, we used thin_lmac=1 as a wifi-device setting
# Now, we support 'firmware_type=thin_lmac' (to better support the fullmac option).
migrate_thin_lmac() {
	local config="$1"

	config_get thin_lmac "$config" thin_lmac
	if [ "$thin_lmac" = 1 ]; then
		uci set "wireless.$config.firmware_type"='thin_lmac'
	fi
	uci delete "wireless.$config.thin_lmac"
}

config_load wireless
config_foreach migrate_thin_lmac wifi-device
