#!/bin/sh
# Remove RAW config sections, and RAW list from AP wifi-iface sections,
# as RAW config is no longer a separate section in wireless config,
# but integrated into wifi-iface sections.

. /lib/functions.sh

del_raw_section() {
	local section="$1"
	uci -q delete "wireless.$section"
}

del_raw_list_from_ap() {
	local section="$1" mode raw_list

	config_get mode "$section" mode
	[ "$mode" = "ap" ] || return 0
	config_get raw_list "$section" raws
	[ -n "$raw_list" ] || return 0

	uci -q delete "wireless.$section.raws"
}

config_load wireless

config_foreach del_raw_section raw
config_foreach del_raw_list_from_ap wifi-iface
