#!/bin/sh

# NB this file is usually _sourced_ via /lib/netifd/dhcp.script,
# so don't 'exit' or introduce any persistent changes to the shell
# environment as it will affect subsequent scripts.

# Only do anything if we've got a new address.
if [ "$1" != bound ]; then
	return 0
fi

# Only attempt to run if configured in uci.
if [ "$(uci -q get wizard-config.main.client)" != 1 ]; then
	return 0
fi

# For now, to reduce potential confusion and security issues, only do this once,
# _even if it fails_.
WC_TMPDIR="$(mktemp -d -t wizard-config.XXXXXX)"
uci -t "$WC_TMPDIR" set wizard-config.main.client=0
uci -t "$WC_TMPDIR" commit
rm -rf "$WC_TMPDIR"

echo Attempting to configure automatically... | logger -t wizard-config -p daemon.info
# Prefer 'serverid' - i.e. DHCP server - if multiple mDNS results.
wizard-config client "${serverid+x}" \
	2> >(logger -t wizard-config -p daemon.info) \
	> >(logger -t wizard-config -p daemon.error)
