#!/bin/sh

# Apply region restrictions.
# Because this runs in early firstboot uci hasn't been set up yet and
# /etc/fw_sys.config and it's fallback /etc/fw_env.config haven't been generated.
# /sbin/persistent_vars_storage.sh works around this by constructing a temporary
# config in /tmp for known board types to make mm_region and mm_region_unlocked accessible.

mm_region="$(persistent_vars_storage.sh READ mm_region)"
mm_region_unlocked="$(persistent_vars_storage.sh READ mm_region_unlocked)"

if [ -n "$mm_region" -a "$mm_region_unlocked" != 1 ]; then
	for fname in $(find /lib/firmware -name "mm_region_${mm_region}_*"); do
		mv "$fname" "$(echo "$fname" | sed "s/mm_region_${mm_region}_//")"
	done
fi

# Remove any unused files to avoid confusion, even if region not set at all.
find /lib/firmware -name 'mm_region_*' -exec rm '{}' +
