#!/bin/sh

# In general, drivers automatically bring up a single managed VIF at wlan?
# (see AUTO_VIF).
#
# In our case, since we want netifd to manage everything, we don't want this. In
# particular, it's a problem if wlan0 comes up when netifd Wi-Fi is completely
# disabled. This happens on first boot with our EKH devices, as they're
# disabled by default since we don't know the user's region.
#
# But the real reason we need this is to make sure we can use the wlan?
# numbering for the _morse_ devices, rather than have some other
# mac80211 device steal it. Once mac80211.sh is loaded by netifd,
# it'll start using phy?-role? naming, so we need to ensure nothing
# else grabs the wlan0/wlan1 slots beforehand.
#
# This logic lives in netifd-morse because it's effectively part of our morse.sh
# setup, even though it technically applies to all Wi-Fi interfaces.
#
# This is more complex than 'just delete the wlan interface because':
#  - some drivers (e.g. brcmfmac) don't allow deletions (so we rename instead)
#  - some drivers (e.g. brcmfmac) take some time for wlan0 to appear
#    after the driver is bound (hence 5 sec timeout)

if [ "$ACTION" != "add" ]; then
	exit 0
fi

log() {
	local lev=$1
	shift
	logger -p "user.$lev" -t remove-auto-vif "$DEVICENAME: $*"
}

generate_iface_name() {
	local suffix
	local iface=$1
	local mac=$(cat "/sys/class/net/$iface/address" 2>/dev/null)

	if [ -z "$mac" ] || [ "$mac" = "00:00:00:00:00:00" ]; then
		# Generate random suffix
		hex1=$(printf "%02x" $((RANDOM % 256)))
		hex2=$(printf "%02x" $((RANDOM % 256)))
		suffix="$hex1-$hex2"
		log info "MAC not available for $iface, using random suffix: $suffix"
	else
		suffix=$(echo "$mac" | awk -F: '{print $(NF-1) "-" $NF}')
	fi

	echo "wlan-$suffix"
}

timeout_secs=5
while [ "$timeout_secs" -gt 0 ]; do
	for f in /sys$DEVPATH/device/net/wlan*; do
		if [ -e "$f" ]; then
			iface="$(basename "$f")"
			if iw dev "$iface" del; then
				log notice "Removed $iface"
			else
				log info "Failed to delete $iface, so falling back to renaming"
				newname="$(generate_iface_name "$iface")"
				ip link set "$iface" down
				if ip link set "$iface" name "$newname"; then
					log info "Renamed $iface to $newname"
				else
					log err "Failed to rename $iface to $newname"
				fi
			fi
			exit 0
		fi
	done

	log info "Waiting for wlan* to exist before removal..."
	sleep 1
	timeout_secs=$((timeout_secs - 1))
done

log err "Timeout waiting for automatic wlan creation of $DEVPATH"
