#!/bin/sh

# These settings would normally be inserted by the morse.sh hotplug
# However, for devices upgraded with configs kept, the hotplug script
# won't be re-run, as the path is already configured.
#
# For this we use a uci default to check for bcf option presence and
# boards we care about.

. /lib/functions.sh

fix_bcf_default() {
	local config="$1"
	config_get type "$config" type
	[ "morse" = "$type" ] || return 1

	uci -q get wireless."${config}".bcf && return 0
	board=$(board_name)
	case "$board" in
		morse,ekh01-03 |\
		morse,ekh03v3)
			bcf=bcf_mf08551.bin
		;;
		morse,ekh01v1)
			bcf=bcf_mf03120.bin
		;;
		morse,ekh01v2)
			bcf=bcf_mf08251.bin
		;;
		morse,ekh04v4)
			bcf=bcf_ekh04_v4.bin
		;;
	esac

	[ -z "$bcf" ] && return 0

	uci -q set wireless."${config}".bcf="${bcf}"
}

config_load wireless
config_foreach fix_bcf_default wifi-device
uci commit wireless
