#!/bin/sh

. /lib/functions.sh
. /lib/netifd/morse/morse_utils.sh

_set_beacon_int_for_wifi_iface() {
	local iface="$1"
	local device="$2"
	local beacon_int="$3"

	# Check if it's the same device
	config_get device_config "$iface" device
	config_get beacon_int_iface "$iface" beacon_int
	if [ "$device_config" = "$device" ] && [ -z $beacon_int_iface ]; then
		uci set wireless."${iface}".beacon_int="$beacon_int"
	fi
}

_get_beacon_int_from_each_device() {
	local config="$1"

	config_get beacon_int "$config" beacon_int
	[ -n "$beacon_int" ] || return 1

	config_foreach _set_beacon_int_for_wifi_iface wifi-iface "$config" "$beacon_int"
	uci delete wireless."${config}".beacon_int
}

config_load wireless
config_foreach _get_beacon_int_from_each_device wifi-device
uci commit wireless
