#!/bin/sh /etc/rc.common

START=90
STOP=50
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/dpp-handler
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

stop_service() {
	# dpp-handler messes with the LEDs. If it's stopped, the LEDs
	# may be in an inconsistent state, and we should reload the
	# system configuration.
	/etc/init.d/led reload
}