#!/bin/sh

if [ "$(uci -q get wizard-config.main.server)" != "" ]; then
	exit 0
fi

if [ "$(persistent_vars_storage.sh READ mm_mode)" = sta ]; then
	uci set wizard-config.main.server=0
	uci set wizard-config.main.client=1
else
	uci set wizard-config.main.server=1
	uci set wizard-config.main.client=0
fi

exit 0
