include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Range Testing Tool UI
LUCI_DEPENDS:=+luci-base luci-light +umdns +luci-lib-httpclient +libiwinfo +iperf3

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature